module.exports = async function handler(req, res) {
  const html = String.raw`<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
  <title>Nanak Dental Clinic | Govindpuri Extension, New Delhi</title>
  <meta name="description" content="Premium dental care website concept for Nanak Dental Clinic in Govindpuri Extension, New Delhi.">
  <meta name="robots" content="noindex,nofollow">
  <meta name="theme-color" content="#0d1b22">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@500;600;700&family=Manrope:wght@400;500;600;700;800&display=swap" rel="stylesheet">
  <style>
    :root{--ink:#0d1b22;--ink2:#1d2c33;--paper:#f7f4ee;--white:#fffdfa;--line:#dedbd2;--muted:#68747a;--teal:#0b6b68;--teal2:#075956;--gold:#b89661;--mist:#e8efec;--shadow:0 24px 70px rgba(13,27,34,.12);--serif:"Cormorant Garamond",Georgia,serif;--sans:"Manrope","Segoe UI",Arial,sans-serif}
    *{box-sizing:border-box}html{scroll-behavior:smooth;scroll-padding-top:92px}body{margin:0;background:var(--paper);color:var(--ink);font-family:var(--sans);line-height:1.6;-webkit-font-smoothing:antialiased}body.lock{overflow:hidden}a{color:inherit;text-decoration:none}button,input,select,textarea{font:inherit}.shell{width:min(1200px,calc(100% - 44px));margin:auto}.serif{font-family:var(--serif)}
    .topline{background:var(--ink);color:#dce6e3;font-size:12px;letter-spacing:.015em}.topline .shell{min-height:38px;display:flex;align-items:center;justify-content:space-between;gap:18px}.topline-left,.topline-right{display:flex;gap:18px;align-items:center}.topline a{opacity:.9}.topline a:hover{opacity:1}.dot{width:4px;height:4px;border-radius:50%;background:#66817d}
    .nav{position:sticky;top:0;z-index:90;background:rgba(247,244,238,.93);backdrop-filter:blur(18px);border-bottom:1px solid rgba(13,27,34,.08)}.navin{height:82px;display:flex;align-items:center;justify-content:space-between;gap:24px}.brand{display:flex;align-items:center;gap:12px;min-width:max-content}.mark{width:44px;height:44px;border:1px solid #cfcac0;border-radius:50%;display:grid;place-items:center;color:var(--teal);background:var(--white)}.brandcopy{line-height:1}.brandcopy strong{display:block;font-family:var(--serif);font-size:22px;letter-spacing:-.02em}.brandcopy span{display:block;margin-top:5px;font-size:9px;letter-spacing:.2em;color:var(--muted);font-weight:800}.navlinks{display:flex;align-items:center;gap:27px;font-size:13px;font-weight:700}.navlinks a{position:relative;color:#314047}.navlinks a:after{content:"";position:absolute;left:0;right:100%;bottom:-7px;height:1px;background:var(--ink);transition:.22s}.navlinks a:hover:after{right:0}.navact{display:flex;align-items:center;gap:10px}.menu{display:none;width:45px;height:45px;border:1px solid #d7d1c8;border-radius:50%;background:var(--white);color:var(--ink)}
    .btn{border:0;border-radius:999px;min-height:48px;padding:0 20px;display:inline-flex;align-items:center;justify-content:center;gap:9px;font-weight:800;font-size:13px;cursor:pointer;transition:transform .2s,box-shadow .2s,background .2s}.btn:hover{transform:translateY(-1px)}.btn.dark{background:var(--ink);color:#fff;box-shadow:0 12px 28px rgba(13,27,34,.18)}.btn.light{background:transparent;border:1px solid #c9c4ba;color:var(--ink)}.btn.teal{background:var(--teal);color:#fff}.icon{width:18px;height:18px;display:inline-block}
    .hero{position:relative;overflow:hidden;padding:58px 0 0}.hero:before{content:"";position:absolute;left:-11vw;top:80px;width:36vw;height:36vw;border:1px solid rgba(11,107,104,.13);border-radius:50%;pointer-events:none}.hero-grid{display:grid;grid-template-columns:.92fr 1.08fr;gap:56px;align-items:center}.eyebrow{display:flex;align-items:center;gap:10px;text-transform:uppercase;letter-spacing:.19em;font-size:10px;font-weight:800;color:var(--teal)}.eyebrow:before{content:"";width:34px;height:1px;background:var(--teal)}h1,h2,h3,p{margin-top:0}h1,h2,h3{font-family:var(--serif);font-weight:600;letter-spacing:-.035em;line-height:.98}h1{font-size:clamp(58px,7vw,96px);margin:18px 0 24px;max-width:690px}h1 em{font-style:italic;color:var(--teal)}.hero-copy>p{font-size:17px;color:#536168;max-width:590px;margin-bottom:28px}.hero-actions{display:flex;gap:10px;flex-wrap:wrap}.hero-note{display:flex;gap:18px;margin-top:28px;flex-wrap:wrap}.hero-note span{font-size:12px;color:#526067;display:flex;gap:8px;align-items:center}.hero-note b{color:var(--ink)}.tinycheck{width:18px;height:18px;border-radius:50%;background:var(--mist);display:grid;place-items:center;color:var(--teal);font-size:11px;font-weight:900}.hero-media{position:relative}.hero-frame{position:relative;height:min(665px,68vw);min-height:540px;overflow:hidden;border-radius:180px 180px 28px 28px;background:#dfe8e5;box-shadow:var(--shadow)}.hero-frame img{width:100%;height:100%;display:block;object-fit:cover;object-position:center 46%}.hero-frame:after{content:"";position:absolute;inset:0;background:linear-gradient(180deg,transparent 62%,rgba(13,27,34,.16));pointer-events:none}.rating-card{position:absolute;left:-44px;bottom:42px;width:220px;background:rgba(255,253,250,.96);backdrop-filter:blur(12px);border:1px solid rgba(255,255,255,.8);padding:18px 20px;border-radius:18px;box-shadow:0 18px 45px rgba(13,27,34,.16)}.rating-card .score{font-family:var(--serif);font-size:35px;line-height:1;color:var(--ink)}.stars{color:var(--gold);letter-spacing:2px;font-size:13px;margin:7px 0 3px}.rating-card small{font-size:10px;color:var(--muted)}
    .trustbar{margin-top:-1px;background:var(--ink);color:#fff}.trustgrid{display:grid;grid-template-columns:repeat(4,1fr)}.trustitem{padding:24px 25px;border-right:1px solid rgba(255,255,255,.1)}.trustitem:last-child{border-right:0}.trustitem b{display:block;font-family:var(--serif);font-size:23px;font-weight:600;line-height:1.1}.trustitem span{display:block;margin-top:4px;font-size:10px;text-transform:uppercase;letter-spacing:.13em;color:#a8b9b6}
    .section{padding:104px 0}.section.white{background:var(--white)}.section.dark{background:var(--ink);color:#fff}.section-head{display:grid;grid-template-columns:.85fr 1.15fr;gap:70px;align-items:end;margin-bottom:56px}.section-head h2,.split-copy h2,.doctor-copy h2,.cta h2{font-size:clamp(46px,5.3vw,72px);margin:13px 0 0}.section-head p{margin:0;color:var(--muted);max-width:610px;font-size:15px}.section.dark .section-head p{color:#aebfbd}.section.dark .eyebrow{color:#8bc4bf}.section.dark .eyebrow:before{background:#8bc4bf}
    .service-list{border-top:1px solid var(--line)}.service{display:grid;grid-template-columns:90px 1.1fr 1fr 40px;gap:24px;align-items:center;padding:29px 0;border-bottom:1px solid var(--line);transition:padding .2s,background .2s}.service:hover{padding-left:12px;padding-right:12px;background:#f1eee7}.service-no{font-family:var(--serif);font-size:20px;color:var(--gold)}.service h3{font-size:34px;margin:0}.service p{margin:0;color:var(--muted);font-size:13px}.service-arrow{width:34px;height:34px;border:1px solid #cbc5ba;border-radius:50%;display:grid;place-items:center;font-size:16px}
    .split{display:grid;grid-template-columns:1.12fr .88fr;gap:70px;align-items:center}.clinic-photo{position:relative;height:620px;border-radius:26px;overflow:hidden;background:#dfe8e5}.clinic-photo img{width:100%;height:100%;display:block;object-fit:cover}.clinic-photo:before{content:"";position:absolute;inset:16px;border:1px solid rgba(255,255,255,.5);border-radius:18px;z-index:2;pointer-events:none}.split-copy h2{margin:15px 0 22px}.split-copy>p{color:var(--muted);font-size:15px}.feature-lines{margin:30px 0 32px;border-top:1px solid var(--line)}.feature-line{display:grid;grid-template-columns:28px 1fr;gap:14px;padding:16px 0;border-bottom:1px solid var(--line)}.feature-line span:first-child{font-family:var(--serif);color:var(--gold);font-size:20px}.feature-line b{font-size:13px;display:block}.feature-line small{color:var(--muted);font-size:11px}
    .doctor-grid{display:grid;grid-template-columns:.72fr 1.28fr;gap:80px;align-items:center}.doctor-panel{min-height:490px;background:linear-gradient(155deg,#154b49,var(--teal2));border-radius:24px;padding:40px;color:#fff;display:flex;flex-direction:column;justify-content:space-between;position:relative;overflow:hidden}.doctor-panel:before,.doctor-panel:after{content:"";position:absolute;border:1px solid rgba(255,255,255,.16);border-radius:50%}.doctor-panel:before{width:330px;height:330px;right:-150px;top:-120px}.doctor-panel:after{width:240px;height:240px;left:-120px;bottom:-110px}.monogram{width:92px;height:92px;border-radius:50%;display:grid;place-items:center;border:1px solid rgba(255,255,255,.45);font-family:var(--serif);font-size:36px;position:relative;z-index:1}.doctor-meta{position:relative;z-index:1}.doctor-meta small{display:block;text-transform:uppercase;letter-spacing:.15em;color:#b8d7d4;font-size:9px}.doctor-meta strong{display:block;font-family:var(--serif);font-size:36px;line-height:1.05;margin:9px 0}.doctor-meta span{font-size:12px;color:#d7e7e5}.doctor-copy h2{margin:15px 0 22px}.doctor-copy p{color:#b8c7c5;max-width:650px}.credential{display:flex;gap:10px;flex-wrap:wrap;margin:28px 0}.credential span{padding:9px 13px;border:1px solid rgba(255,255,255,.18);border-radius:999px;font-size:10px;color:#dce8e6}.doctor-copy .btn.light{color:#fff;border-color:rgba(255,255,255,.3)}
    .reviews{display:grid;grid-template-columns:1.25fr .75fr;gap:26px}.review-main,.review-stack>div{background:#f0ede6;border:1px solid #ddd7cc;border-radius:22px}.review-main{padding:42px}.quote{font-family:var(--serif);font-size:40px;line-height:1.05;letter-spacing:-.025em}.review-main .stars{margin-top:28px}.review-main small,.review-stack small{color:var(--muted);font-size:10px;text-transform:uppercase;letter-spacing:.11em}.review-stack{display:grid;gap:18px}.review-stack>div{padding:28px}.review-stack p{font-family:var(--serif);font-size:25px;line-height:1.12;margin-bottom:20px}
    .process{display:grid;grid-template-columns:repeat(3,1fr);gap:18px}.step{padding:30px 28px;border-top:1px solid #bcb6ab}.step .n{font-family:var(--serif);font-size:20px;color:var(--gold)}.step h3{font-size:31px;margin:26px 0 11px}.step p{font-size:12px;color:var(--muted);margin:0}
    .cta{padding:92px 0}.cta-box{background:var(--teal);color:#fff;border-radius:30px;padding:58px 60px;display:grid;grid-template-columns:1.2fr .8fr;gap:50px;align-items:center;position:relative;overflow:hidden}.cta-box:after{content:"";position:absolute;width:430px;height:430px;border-radius:50%;border:1px solid rgba(255,255,255,.18);right:-170px;top:-160px}.cta .eyebrow{color:#c7e2df}.cta .eyebrow:before{background:#c7e2df}.cta h2{margin:12px 0 12px;color:#fff}.cta p{color:#d6e8e5;margin:0;max-width:650px}.cta-actions{display:flex;justify-content:flex-end;gap:10px;flex-wrap:wrap;position:relative;z-index:1}.cta .btn.dark{background:#fff;color:var(--ink)}.cta .btn.light{color:#fff;border-color:rgba(255,255,255,.42)}
    footer{background:#091419;color:#d1dcda;padding:62px 0 26px}.footer-grid{display:grid;grid-template-columns:1.35fr .7fr .95fr 1fr;gap:42px}.footer-brand .brand{color:#fff}.footer-brand .mark{background:transparent;border-color:#536165;color:#cce0dc}.footer-brand p{font-size:11px;color:#829397;max-width:360px;margin-top:20px}.footer-col h4{font-size:10px;text-transform:uppercase;letter-spacing:.15em;color:#789094;margin:4px 0 17px}.footer-col a,.footer-col span{display:block;font-size:12px;color:#c2cecc;margin:9px 0}.footer-bottom{border-top:1px solid rgba(255,255,255,.08);margin-top:42px;padding-top:20px;display:flex;justify-content:space-between;gap:18px;flex-wrap:wrap;font-size:10px;color:#718388}
    .mobilebar{display:none;position:fixed;left:12px;right:12px;bottom:calc(12px + env(safe-area-inset-bottom));z-index:85;background:rgba(13,27,34,.96);backdrop-filter:blur(14px);padding:8px;border-radius:18px;box-shadow:0 18px 45px rgba(0,0,0,.28);gap:8px}.mobilebar a{flex:1;min-height:46px;border-radius:12px;display:flex;align-items:center;justify-content:center;font-size:12px;font-weight:800;color:#fff}.mobilebar .book{background:var(--teal)}
    .modalback{display:none;position:fixed;inset:0;z-index:200;background:rgba(6,18,23,.72);backdrop-filter:blur(8px);padding:20px;align-items:center;justify-content:center}.modalback.open{display:flex}.modal{width:min(640px,100%);max-height:90dvh;overflow:auto;background:var(--white);border-radius:26px;box-shadow:0 35px 100px rgba(0,0,0,.3)}.modalhead{position:relative;padding:30px 32px 22px;background:var(--ink);color:#fff}.modalhead h2{font-size:42px;margin:5px 46px 6px 0}.modalhead p{font-size:12px;color:#aebfbd;margin:0}.close{position:absolute;right:18px;top:18px;width:40px;height:40px;border:1px solid rgba(255,255,255,.25);border-radius:50%;background:transparent;color:#fff;font-size:22px;cursor:pointer}.form{padding:26px 32px 30px;display:grid;grid-template-columns:1fr 1fr;gap:15px}.field{display:flex;flex-direction:column;gap:7px}.field.full{grid-column:1/-1}.field label{font-size:10px;text-transform:uppercase;letter-spacing:.12em;font-weight:800;color:#536168}.field input,.field select,.field textarea{width:100%;border:1px solid #d9d4ca;background:#faf8f3;border-radius:12px;padding:12px 13px;outline:none;color:var(--ink);font-size:14px}.field input:focus,.field select:focus,.field textarea:focus{border-color:var(--teal);box-shadow:0 0 0 3px rgba(11,107,104,.1)}.field textarea{min-height:86px;resize:vertical}.submit{grid-column:1/-1;min-height:50px;border:0;border-radius:999px;background:var(--teal);color:#fff;font-weight:800;cursor:pointer}.formnote{grid-column:1/-1;font-size:10px;color:var(--muted);text-align:center}
    @media(max-width:1000px){.navlinks{display:none;position:absolute;top:82px;left:0;right:0;background:var(--paper);padding:18px 24px 24px;border-bottom:1px solid #d9d4ca;flex-direction:column;align-items:flex-start;gap:0}.navlinks.open{display:flex}.navlinks a{padding:11px 0;width:100%}.menu{display:grid;place-items:center}.navact>.btn{display:none}.hero-grid{grid-template-columns:1fr;gap:38px}.hero-copy{padding-top:10px}.hero-frame{height:680px;max-width:760px;margin:auto}.rating-card{left:18px}.trustgrid{grid-template-columns:repeat(2,1fr)}.trustitem:nth-child(2){border-right:0}.trustitem:nth-child(-n+2){border-bottom:1px solid rgba(255,255,255,.1)}.section-head,.split,.doctor-grid,.cta-box{grid-template-columns:1fr;gap:38px}.service{grid-template-columns:62px 1fr 40px}.service p{grid-column:2/3;margin-top:-10px}.reviews{grid-template-columns:1fr}.footer-grid{grid-template-columns:1fr 1fr}.footer-brand{grid-column:1/-1}.cta-actions{justify-content:flex-start}}
    @media(max-width:680px){.shell{width:min(100% - 28px,1200px)}.topline .shell{justify-content:center}.topline-right,.topline .dot,.topline-left a:nth-of-type(2){display:none}.navin{height:70px}.navlinks{top:70px}.brandcopy strong{font-size:19px}.brandcopy span{font-size:8px}.mark{width:40px;height:40px}.hero{padding-top:30px}.hero:before{display:none}h1{font-size:55px}.hero-copy>p{font-size:15px}.hero-frame{height:500px;min-height:0;border-radius:120px 120px 20px 20px}.hero-frame img{object-position:center 45%}.rating-card{left:12px;right:12px;bottom:14px;width:auto;display:flex;align-items:center;justify-content:space-between;padding:13px 16px}.rating-card .score{font-size:28px}.rating-card .stars{margin:0}.rating-card small{display:none}.trustgrid{grid-template-columns:1fr 1fr}.trustitem{padding:18px 14px}.trustitem b{font-size:19px}.trustitem span{font-size:8px}.section{padding:76px 0}.section-head{margin-bottom:34px}.section-head h2,.split-copy h2,.doctor-copy h2,.cta h2{font-size:46px}.service{grid-template-columns:42px 1fr 32px;gap:12px;padding:22px 0}.service h3{font-size:28px}.service p{font-size:11px}.clinic-photo{height:430px}.doctor-panel{min-height:380px;padding:28px}.doctor-meta strong{font-size:31px}.quote{font-size:32px}.review-main{padding:30px}.process{grid-template-columns:1fr}.step{padding:24px 0}.cta{padding:64px 0}.cta-box{padding:36px 25px;border-radius:22px}.footer-grid{grid-template-columns:1fr 1fr;gap:28px}.footer-brand{grid-column:1/-1}.mobilebar{display:flex}.footer-bottom{padding-bottom:78px}.modalback{padding:0;align-items:flex-end}.modal{border-radius:24px 24px 0 0;max-height:92dvh}.modalhead{padding:24px 20px 18px}.modalhead h2{font-size:34px}.form{padding:20px;grid-template-columns:1fr}.field.full,.submit,.formnote{grid-column:auto}}
    @media(prefers-reduced-motion:reduce){*{scroll-behavior:auto!important;transition:none!important}}
  </style>
</head>
<body>
  <div class="topline"><div class="shell"><div class="topline-left"><a href="tel:+919999608619">+91 99996 08619</a><span class="dot"></span><a href="https://www.google.com/maps/search/?api=1&query=Shop%20No.%201%2C%201664A%2F15%2C%20near%20Durga%20Mata%20Mandir%2C%20Govindpuri%20Extension%2C%20New%20Delhi%2C%20Delhi%20110019" target="_blank" rel="noopener">Govindpuri Extension, New Delhi</a></div><div class="topline-right"><span>Daily 10 AM – 9 PM · public listing</span></div></div></div>
  <nav class="nav"><div class="shell navin"><a class="brand" href="#home"><span class="mark"><svg width="24" height="24" viewBox="0 0 64 64" fill="none"><path d="M18 7c5 0 8 3 14 3s9-3 14-3c8 0 13 6 13 15 0 10-5 16-8 24-2 6-4 11-8 11-4 0-5-6-6-12-1-6-2-10-5-10s-4 4-5 10c-1 6-2 12-6 12-4 0-6-5-8-11-3-8-8-14-8-24C5 13 10 7 18 7Z" stroke="currentColor" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"/><path d="M22 16c5 3 15 3 20 0" stroke="currentColor" stroke-width="3" stroke-linecap="round"/></svg></span><span class="brandcopy"><strong>Nanak Dental Clinic</strong><span>CARE · COMFORT · CONFIDENCE</span></span></a><div class="navlinks" id="navlinks"><a href="#services">Treatments</a><a href="#clinic">Clinic</a><a href="#doctor">Doctor</a><a href="#reviews">Reviews</a><a href="#visit">Visit</a></div><div class="navact"><a class="btn dark" href="#appointment" data-book>Request appointment</a><button class="menu" id="menu" aria-label="Open menu" aria-expanded="false">☰</button></div></div></nav>
  <main id="home">
    <section class="hero"><div class="shell"><div class="hero-grid"><div class="hero-copy"><div class="eyebrow">Dentistry in Govindpuri Extension</div><h1>A calmer standard of <em>dental care.</em></h1><p>Modern, patient-focused dentistry with specialist services, clear appointment access and a strong local reputation — presented with the care the clinic deserves.</p><div class="hero-actions"><a class="btn dark" href="#appointment" data-book>Request appointment</a><a class="btn light" href="tel:+919999608619">Call the clinic</a></div><div class="hero-note"><span><i class="tinycheck">✓</i><b>4.9</b> Google rating</span><span><i class="tinycheck">✓</i>Implantology listed</span><span><i class="tinycheck">✓</i>Emergency dental care listed</span></div></div><div class="hero-media"><div class="hero-frame"><img src="https://oupovxujjshindzgflgz.supabase.co/functions/v1/nanak-assets-v2?img=hero&asset=doctor-patient-v1" alt="Dental patient consultation visual for Nanak Dental Clinic website concept"></div><div class="rating-card"><div><div class="score">4.9 / 5</div><div class="stars">★★★★★</div></div><small>154 Google reviews · Aug 2026 snapshot</small></div></div></div></div></section>
    <div class="trustbar"><div class="shell trustgrid"><div class="trustitem"><b>4.9 / 5</b><span>Google rating</span></div><div class="trustitem"><b>154</b><span>Public reviews</span></div><div class="trustitem"><b>10 AM – 9 PM</b><span>Daily listing</span></div><div class="trustitem"><b>Dr. Sukhpreet Singh</b><span>Dentist & Implantologist</span></div></div></div>
    <section class="section white" id="services"><div class="shell"><div class="section-head"><div><div class="eyebrow">Treatments</div><h2>Focused care, without the clutter.</h2></div><p>The clinic’s public listings cover everyday dentistry as well as specialist fields. Treatment suitability and final recommendations always depend on a clinical assessment.</p></div><div class="service-list"><div class="service"><div class="service-no">01</div><h3>Dental Implants</h3><p>Implantology is publicly listed for the clinic and for Dr. Sukhpreet Singh.</p><div class="service-arrow">↗</div></div><div class="service"><div class="service-no">02</div><h3>Root Canal Care</h3><p>Endodontics is named among the clinic’s public fields of dentistry.</p><div class="service-arrow">↗</div></div><div class="service"><div class="service-no">03</div><h3>Orthodontics</h3><p>Orthodontic treatment is listed among the clinic’s available dental fields.</p><div class="service-arrow">↗</div></div><div class="service"><div class="service-no">04</div><h3>Cosmetic Dentistry</h3><p>The current Google profile categorizes the clinic as a cosmetic dentist.</p><div class="service-arrow">↗</div></div><div class="service"><div class="service-no">05</div><h3>Crowns & Veneers</h3><p>Public service listings include crowns and veneers, subject to assessment.</p><div class="service-arrow">↗</div></div><div class="service"><div class="service-no">06</div><h3>Emergency Dental Care</h3><p>The current Google profile includes emergency dental service.</p><div class="service-arrow">↗</div></div></div></div></section>
    <section class="section" id="clinic"><div class="shell split"><div class="clinic-photo"><img src="https://oupovxujjshindzgflgz.supabase.co/functions/v1/nanak-assets-v2?img=interior" alt="Modern dental clinic interior visual"></div><div class="split-copy"><div class="eyebrow">The clinic</div><h2>Clinical precision. Human warmth.</h2><p>The redesign intentionally avoids the cold, generic hospital-template look. Clear hierarchy, calmer spacing and focused trust signals make the experience easier to understand before a patient ever calls.</p><div class="feature-lines"><div class="feature-line"><span>01</span><div><b>Local trust</b><small>4.9 rating from 154 Google reviews in the August 2026 snapshot.</small></div></div><div class="feature-line"><span>02</span><div><b>Clear access</b><small>Direct call, WhatsApp appointment request and map directions.</small></div></div><div class="feature-line"><span>03</span><div><b>Specialist visibility</b><small>Implantology, endodontics, orthodontics and cosmetic dentistry are surfaced clearly.</small></div></div></div><a class="btn light" href="#appointment" data-book>Plan your visit</a></div></div></section>
    <section class="section dark" id="doctor"><div class="shell doctor-grid"><div class="doctor-panel"><div class="monogram">SS</div><div class="doctor-meta"><small>Public profile snapshot</small><strong>Dr. Sukhpreet Singh</strong><span>Dentist & Implantologist · BDS</span></div></div><div class="doctor-copy"><div class="eyebrow">Doctor profile</div><h2>Experience patients can understand at a glance.</h2><p>Practo publicly lists Dr. Sukhpreet Singh as a Dentist and Implantologist with BDS qualification, a claimed profile and verified medical registration. The previous clinic research snapshot also listed 18 years of overall experience.</p><div class="credential"><span>BDS</span><span>Dentist</span><span>Implantologist</span><span>Delhi State Dental Council registration listed</span></div><a class="btn light" href="#appointment" data-book>Request a consultation</a></div></div></section>
    <section class="section white" id="reviews"><div class="shell"><div class="section-head"><div><div class="eyebrow">Patient reputation</div><h2>Proof should feel quiet, not loud.</h2></div><p>These are paraphrased themes from the clinic’s public Google review snapshot rather than invented testimonials.</p></div><div class="reviews"><div class="review-main"><div class="quote">“Patients repeatedly highlight experienced care, treatment quality and value.”</div><div class="stars">★★★★★</div><small>Public Google review themes · paraphrased</small></div><div class="review-stack"><div><p>“Implant care and treatment value stand out in positive feedback.”</p><small>Review theme · paraphrased</small></div><div><p>“Service quality and affordability appear as recurring signals.”</p><small>Review theme · paraphrased</small></div></div></div></div></section>
    <section class="section"><div class="shell"><div class="section-head"><div><div class="eyebrow">Your visit</div><h2>Simple from first tap to clinic chair.</h2></div><p>The appointment flow stays on the current page. Patients enter their preferred details in a clean popup, then continue on WhatsApp without the website storing medical information.</p></div><div class="process"><div class="step"><div class="n">01</div><h3>Choose</h3><p>Select the treatment or reason for your visit and a preferred date.</p></div><div class="step"><div class="n">02</div><h3>Send</h3><p>The form prepares a clear appointment request and opens WhatsApp.</p></div><div class="step"><div class="n">03</div><h3>Confirm</h3><p>The clinic can confirm timing directly with the patient.</p></div></div></div></section>
    <section class="cta" id="visit"><div class="shell"><div class="cta-box"><div><div class="eyebrow">Govindpuri Extension</div><h2>Ready to request an appointment?</h2><p>Shop No. 1, 1664A/15, near Durga Mata Mandir, Govindpuri Extension, New Delhi, Delhi 110019.</p></div><div class="cta-actions"><a class="btn dark" href="#appointment" data-book>Request appointment</a><a class="btn light" href="https://www.google.com/maps/search/?api=1&query=Shop%20No.%201%2C%201664A%2F15%2C%20near%20Durga%20Mata%20Mandir%2C%20Govindpuri%20Extension%2C%20New%20Delhi%2C%20Delhi%20110019" target="_blank" rel="noopener">Get directions</a></div></div></div></section>
  </main>
  <footer><div class="shell"><div class="footer-grid"><div class="footer-brand"><a class="brand" href="#home"><span class="mark"><svg width="24" height="24" viewBox="0 0 64 64" fill="none"><path d="M18 7c5 0 8 3 14 3s9-3 14-3c8 0 13 6 13 15 0 10-5 16-8 24-2 6-4 11-8 11-4 0-5-6-6-12-1-6-2-10-5-10s-4 4-5 10c-1 6-2 12-6 12-4 0-6-5-8-11-3-8-8-14-8-24C5 13 10 7 18 7Z" stroke="currentColor" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"/></svg></span><span class="brandcopy"><strong>Nanak Dental Clinic</strong><span>GOVINDPURI · NEW DELHI</span></span></a><p>Premium website concept built from the clinic information and public-profile snapshot already researched for this project. Clinic verification is recommended before official public launch.</p></div><div class="footer-col"><h4>Explore</h4><a href="#services">Treatments</a><a href="#clinic">Clinic</a><a href="#doctor">Doctor</a><a href="#reviews">Reviews</a></div><div class="footer-col"><h4>Contact</h4><a href="tel:+919999608619">+91 99996 08619</a><a href="https://wa.me/919999608619" target="_blank" rel="noopener">WhatsApp</a><span>Daily 10 AM – 9 PM · public listing</span></div><div class="footer-col"><h4>Visit</h4><a href="https://www.google.com/maps/search/?api=1&query=Shop%20No.%201%2C%201664A%2F15%2C%20near%20Durga%20Mata%20Mandir%2C%20Govindpuri%20Extension%2C%20New%20Delhi%2C%20Delhi%20110019" target="_blank" rel="noopener">Shop No. 1, 1664A/15<br>near Durga Mata Mandir<br>Govindpuri Extension, New Delhi 110019</a></div></div><div class="footer-bottom"><span>© 2026 Nanak Dental Clinic website concept</span><span>Public-information snapshot · August 2026</span></div></div></footer>
  <div class="mobilebar"><a href="tel:+919999608619">Call clinic</a><a class="book" href="#appointment" data-book>Appointment</a></div>
  <div class="modalback" id="modal" aria-hidden="true"><div class="modal" role="dialog" aria-modal="true" aria-labelledby="modalTitle"><div class="modalhead"><button class="close" id="close" aria-label="Close appointment form">×</button><div class="eyebrow">Appointment request</div><h2 id="modalTitle">Tell the clinic what you need.</h2><p>Your details are not stored on this website. The request continues on WhatsApp.</p></div><form class="form" id="appointmentForm"><div class="field"><label for="name">Name *</label><input id="name" name="name" autocomplete="name" required></div><div class="field"><label for="phone">Phone *</label><input id="phone" name="phone" inputmode="tel" autocomplete="tel" required></div><div class="field"><label for="service">Treatment / reason</label><select id="service" name="service"><option>General consultation</option><option>Dental Implants</option><option>Root Canal</option><option>Orthodontics</option><option>Cosmetic Dentistry</option><option>Crowns / Veneers</option><option>Emergency Dental Care</option><option>Other</option></select></div><div class="field"><label for="date">Preferred date</label><input id="date" name="date" type="date"></div><div class="field"><label for="time">Preferred time</label><select id="time" name="time"><option>Flexible</option><option>10 AM – 1 PM</option><option>1 PM – 5 PM</option><option>5 PM – 9 PM</option></select></div><div class="field full"><label for="note">Note</label><textarea id="note" name="message" placeholder="Briefly tell the clinic what you need help with (optional)"></textarea></div><button class="submit" type="submit">Continue on WhatsApp</button><div class="formnote">No information entered here is stored by this website.</div></form></div></div>
  <script>
    (()=>{const menu=document.getElementById('menu'),links=document.getElementById('navlinks'),modal=document.getElementById('modal'),close=document.getElementById('close'),form=document.getElementById('appointmentForm'),date=document.getElementById('date');if(date){const d=new Date(),y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');date.min=y+'-'+m+'-'+day}if(menu&&links){menu.addEventListener('click',()=>{const o=links.classList.toggle('open');menu.setAttribute('aria-expanded',String(o));menu.textContent=o?'×':'☰'});links.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{links.classList.remove('open');menu.setAttribute('aria-expanded','false');menu.textContent='☰'}))}const openModal=()=>{modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.classList.add('lock');setTimeout(()=>document.getElementById('name')?.focus(),60)};const closeModal=()=>{modal.classList.remove('open');modal.setAttribute('aria-hidden','true');document.body.classList.remove('lock')};document.querySelectorAll('[data-book]').forEach(el=>el.addEventListener('click',e=>{e.preventDefault();openModal()}));close.addEventListener('click',closeModal);modal.addEventListener('click',e=>{if(e.target===modal)closeModal()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&modal.classList.contains('open'))closeModal()});form.addEventListener('submit',e=>{e.preventDefault();const d=new FormData(form),name=String(d.get('name')||'').trim(),phone=String(d.get('phone')||'').trim();if(!name||!phone){alert('Please enter your name and phone number.');return}const lines=['Hello Nanak Dental Clinic, I would like to request an appointment.','Name: '+name,'Phone: '+phone,'Treatment / Reason: '+String(d.get('service')||'General consultation'),'Preferred date: '+String(d.get('date')||'Flexible'),'Preferred time: '+String(d.get('time')||'Flexible'),'Note: '+String(d.get('message')||'No additional note')];window.location.href='https://wa.me/919999608619?text='+encodeURIComponent(lines.join('\n'))})})();
  </script>
</body>
</html>`;
  res.status(200);
  res.setHeader('content-type', 'text/html; charset=utf-8');
  res.setHeader('cache-control', 'no-store, no-cache, must-revalidate, max-age=0');
  res.setHeader('cdn-cache-control', 'no-store');
  res.setHeader('vercel-cdn-cache-control', 'no-store');
  res.setHeader('pragma', 'no-cache');
  res.setHeader('expires', '0');
  res.setHeader('x-nanak-version', 'v6-premium-editorial');
  return res.send(html);
};
